### ISSUE TITLE
Feature: Cross node support

### ISSUE THREAD

**Issue by GregSutcliffe** [torrancew/hiera-foreman#2]
Presently I describe a cluster of machines with a YAML file that I load with Hiera. It looks something like:

```

---
servers:
  server1:
    type: loadbalancer
    ssl_cert: foo.example.com
  server2:
    type appserver
    apps:
      app1:
        threads: 2
        port: 3001
      app2:
        threads: 2
        port: 3002
```

I have puppet code which does things with the whole file. So for example, the loadbalancer needs to know about the appservers it is forwarding to. Presently I do this using some puppet code like:

$servers=hiera('servers')

file { 'my-nginx-loadbalancer': content => template('nginx/loadbalancer') }

and the template then uses Ruby and things like servers.map{} to get all of the apps and all of the ports and appserver names and write them out correctly. This is all fine (if hacky)

Now, I can easily add the data above to Foreman (so Host 'server2' could have a Parameter "app2 = 3001,2") and then it can be processed in the template _but_ I cannot query that data from the loadbalancer, as the code looks directly to $fqdn. 

In all honesty, I probably need to remodel my puppet code (it's hacky, I agree) but the idea of querying wider Foreman data seemed useful, so I'm throwing it out there.
